### ISSUE TITLE
Bug ( symlink / typechange ): ImgBot is deleting files

### ISSUE THREAD

**Issue by acid-chicken** [dabutvin/ImgBot#103]
From acid-chicken/papirus-icon-theme#1

ImgBot is deleting some SVG files (not all of the SVG files).
Would you fix this bug?

![image](https://user-images.githubusercontent.com/20679825/42725254-f33b4ffe-87bb-11e8-9ede-97493388b00d.png)

**Comment by dabutvin** [comment]
whoah. that if very strange - have not seen this behavior anywhere before. Thanks for flagging it here.

We only operate a defined set of image extensions https://github.com/dabutvin/ImgBot/blob/master/ImgBot.Common/KnownImgPatterns.cs

I'm going to fork and see if it repros. Maybe it is having trouble checking them out properly

**Comment by dabutvin** [comment]
okay I repro'd this issue.

It appears to be something to do with symlinks and typechange.

I'm not familiar with these concepts, but there is definitely a bug here. Nice find!

You can see the behavior by cloning 

```
git clone https://github.com/PapirusDevelopmentTeam/papirus-icon-theme
git status
```

```
        typechange: Papirus/16x16/apps/Abricotine.svg
	typechange: Papirus/16x16/apps/Anatine.svg
	typechange: Papirus/16x16/apps/Blender.svg
	typechange: Papirus/16x16/apps/FBReader.svg
	typechange: Papirus/16x16/apps/GitKraken.svg
        ...
```

when libgit runs the clone all these files get added to the stage as deleted files for some reason.

we may be able to work around this by running a reset right after clone
we may also get better behavior by moving ImgBot to linux see https://github.com/dabutvin/ImgBot/issues/60#issuecomment-404987925

**Comment by dabutvin** [comment]
More research or knowledge on symbolic is links is needed to figure out the next steps here

**Comment by guntbert** [comment]
Bump!

**Comment by dabutvin** [comment]
with the new infrastructure changes recently rolled out as part of #341 , this is no longer an issue !!

Verified at https://github.com/dabutvin/papirus-icon-theme/pull/2

Took a while, but we finally got there 👍
