### ISSUE TITLE
Ignore forks

### ISSUE THREAD

**Issue by martincostello** [dabutvin/Imgbot#105]
I've installed ImgBot into my account for all repos as it means I'll get all the benefits going forwards without any additional configuration, but it's generating a lot of noise by opening PRs against forks I've made of other users' and orgs' repositories.

When installed into a personal account, ImgBot should ignore forks by default when scoped to the whole account, to reduce noise and wasted effort optimising images for repos that the user does not own, particularly ones that user does not regularly contribute to.

Here's an example: martincostello/xunit.github.io#1

**Comment by dabutvin** [comment]
Hi @martincostello ! This is an awesome idea. Thanks for opening an issue 😎 

Here's my initial thoughts :

I believe most of the GitHub webhooks that we listen to will say `fork : true | false` in the payload. And if that's not available, I'm sure the GitHub API will tell us whether it is a fork or not.

For configuring it, right now we have `.imgbotconfig` (https://imgbot.net/docs#configuration) but this is only configuration at the repo level, not settings across repos. So adding a setting there won't make a lot of sense.

There are a number of projects on GitHub that fork and continue from there and I would hate to exclude them from ImgBot.

I wonder if GitHub is going to have any changes in the future to their repo selection UI that could help us here. I have asked in the forums for any advice here (https://platform.github.community/t/install-in-all-repos-except-forks/6587)

I am open to any other ideas anyone has to move this forward

**Comment by martincostello** [comment]
Thanks @dabutvin. That all makes sense, I guess something account level from GitHub’s POV would have the most utility and usability, rather than either blanket cutting off forks completely, or requiring the user to maintain a list of repos.

Hopefully at some point the settings for apps can get enough flexibility to enable this sort of scenario.

The only other thing I can think of is that some bots seem to support a central config repo in the account for convention-based settings, but of course that requires users to pre-configure the bot before even setting it up.

**Comment by dabutvin** [comment]
Interesting! 
so for the case where you installed in all repos + future repos, you would create a new repo yourself called `martinconstello/.imgbot` or something like that to hold account level configuration like disabling forks or other account level configurations.

That's a really cool idea

**Comment by martincostello** [comment]
Yeah, something like that. I’ll try and find a link to example tomorrow, I couldn’t seem to find one in the mobile view just now.

**Comment by martincostello** [comment]
I forgot to provide you with an example!

The [settings](https://probot.github.io/apps/settings/) bot seems to support something like a configuration repository.

**Comment by dabutvin** [comment]
hey @martincostello 
This is a really cool app! Thanks for sharing, I never heard of this before.

The way this works is [probot-config](https://github.com/probot/probot-config) replicates your settings from the `.github` repo across the repos that you install it in. So for the ImgBot case, you could make a `.github` repo that contains a `.imgbotconfig` file and the probot would replicate it across all your repos as you made changes.


Here is probot's .github repo for reference: https://github.com/probot/.github It contains a stale config right now

**Comment by snarfed** [comment]
hi! i'd very much like this option too. the .github repo + `.imgbotconfig` file approach would work, but would be very heavyweight for users. most other github apps i've used offer options like these in their web UI instead. i know that might be more work, but it would definitely be easier and better usability. maybe something to consider?

ImgBot is great, btw! thank you for making and running it!

**Comment by dabutvin** [comment]
Hey @snarfed thanks for digging this up!

Now that we started work on #497 we can tack on this setting as well - would fit right in actually.

Let's reactivate

**Comment by dabutvin** [comment]
Here are the steps required:

1. follow along with #497 and add a setting backend that cuts across repos. Maybe url can be `/settings/{installationid}/. We can use the same settings table we are using for repos, but instead of repositoryId use some slug like 'all'
2. Add a settings UI to read and write to this backend and include the "ignore forks" option. This would be global settings instead of repository level settings.
3. Read and respect the ignore forks in the [main webhook](https://github.com/dabutvin/Imgbot/blob/master/WebHook/WebHookFunction.cs) and cancel work when this setting is enabled
4. Add [tests for the webhook](https://github.com/dabutvin/Imgbot/blob/master/Test/WebHookTests.cs) to assert this behavior
5. Update [the docs](https://github.com/dabutvin/Imgbot/tree/master/Docs) with the new configuration option
