### ISSUE TITLE
Increase compression function timeout

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#112]
Default is at 5 minutes, we can increase to 10 minutes for those extra big repos

https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#consumption-plan

**Comment by rajat13** [comment]
Hi I am new to open-source and want to accomplish this task. Please tell me the next step.

**Comment by dabutvin** [comment]
Hi @rajat13! Welcome. Glad you found your way here 🎉 

We are using Azure Functions platform to optimize images and this task is to change the settings for the CompressImagesFunction. Specifically to increase the timeout.

You can get to the host configuration file here: https://github.com/dabutvin/ImgBot/blob/master/CompressImagesFunction/host.json

You will notice that this file is empty. We are using just the defaults right now. This will be our first customization.

The full reference for the host.json file can be found here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json

For some tips to get the project running locally see the contributing section of the docs: https://imgbot.net/docs#contributing

Good luck! Post here with any updates or questions that come up

**Comment by dabutvin** [comment]
Let's open this back up and see if anyone wants to do this for hacktoberfest?

**Comment by mwanchap** [comment]
I was going to have a crack at this, but looks like it's already been done in #185 ?

**Comment by dabutvin** [comment]
oh whoops. Thanks for pointing that out.
I thought it closed with the PR
