### ISSUE TITLE
Bug: ImgBot deletes Jupyter Notebook

### ISSUE THREAD

**Issue by RohanNagar** [dabutvin/ImgBot#121]
As seen in: RohanNagar/datasciencelab-utaustin#2 and RohanNagar/datasciencelab-utaustin#1

`lab10/lab10.ipynb` is completely deleted in the PR. It's interesting that only that `.ipynb` file is deleted, and not any of the others.

It's not an issue for me as I don't maintain that project any more, but I thought it would be a good idea to open a bug report in case others are having this issue too.

**Comment by dabutvin** [comment]
Thanks for reporting this. Glad it's not an issue for you right now, but this a pretty critical problem.

I wonder if it is related to #103 at all?

When I clone https://github.com/RohanNagar/datasciencelab-utaustin on my laptop it marks a file as modified right away

```
modified:   lab10/Lab10.ipynb
```

Will have to do some research into these file types

**Comment by RohanNagar** [comment]
> When I clone https://github.com/RohanNagar/datasciencelab-utaustin on my laptop it marks a file as modified right away

That's interesting.. I wonder why that is happening. I just tried to clone it from a clean machine and don't see it marked as modified by git.. I'll see if I can figure out more about that.

**Comment by dabutvin** [comment]
fixed in #123
