### ISSUE TITLE
Bot created branch with compressed versions but didn't create a PR

### ISSUE THREAD

**Issue by johnathan99j** [dabutvin/ImgBot#147]
It's been several hours and it's worked on several other repos of mine since, anyway [here's the commit](https://github.com/URN/URN-iOS/commit/c18af0f3f8313962e2398231e850e4a9ca73d359).

That aside, sweet bot!

**Comment by johnathan99j** [comment]
Having now done some searching I can see that #88 is related

**Comment by dabutvin** [comment]
Yep. This is a known issue right now. Thanks for reporting. You can follow the status of the fix here: 
https://github.com/dabutvin/ImgBot/issues/144

I don't know why this started happening so frequently. It's not a failure to open the PR, it never gets the message at all. Anyways, I think listening to the webhook from GitHub will be a better model anyways.

**Comment by johnathan99j** [comment]
Thanks, will the fix work retrospectively or should I just manually sort the current stalled branches?

**Comment by dabutvin** [comment]
fixed in #151 

Now we will queue an `OpenPrMessage` when GitHub tells us the imgbot branch gets pushed to

**Comment by dabutvin** [comment]
Thanks for reporting the problem! Let me know if anything else comes up
