### ISSUE TITLE
📝 Sign A CLA [Needed for Contribution] 📝

### ISSUE THREAD

**Issue by AYIDouble** [dabutvin/ImgBot#178]
It would be nice if the Bot signed the CLA from Google, 
for Contributions to Google Repositories.
It's a really easy Task that can be done in 3 minutes.

https://github.com/google/blockly/pull/2064

https://github.com/google/audion/pull/85

https://github.com/google/wear-screeninfo/pull/1

https://github.com/google/ioweb2015/pull/1542

https://github.com/google/virtual-tutors/pull/1

https://github.com/google/nogotofail/pull/118

> So there's good news and bad news.
> 
> +1 The good news is that everyone that needs to sign a CLA (the pull request submitter and all commit authors) have done so. Everything is all good there.
> 
> confused The bad news is that it appears that one or more commits were authored or co-authored by someone other than the pull request submitter. We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that here in the pull request.
> 
> Note to project maintainer: This is a terminal state, meaning the cla/google commit status will not change from this state. It's up to you to confirm consent of all the commit author(s), set the cla label to yes (if enabled on your project), and then merge this pull request when appropriate.

**Comment by dabutvin** [comment]
Cool! There shouldn't be any problem doing this. I can log in and take care of this later tonight

Thanks!

**Comment by dabutvin** [comment]
So the @ImgBotApp account has already signed the CLA at https://cla.developers.google.com/clas

Not sure what the issue is here

**Comment by AYIDouble** [comment]
That's weird, https://cla.developers.google.com/clas shows me that I have signed it too.
I don't see what the problem could be, I need to look deeper at it.

**Comment by liach** [comment]
I'm curious if the bot can sign any cla application, such as the one here: https://github.com/Railcraft/Railcraft/pull/1512#issuecomment-430533968

**Comment by dabutvin** [comment]
@liach done :)

**Comment by webknjaz** [comment]
Could bot sign this as well? https://github.com/vespene-io/vespene/pull/29#issuecomment-434112048

**Comment by dabutvin** [comment]
@webknjaz done :)

**Comment by webknjaz** [comment]
Thanks :)

**Comment by mrmajik45** [comment]
I need the Google CLA Signed. https://github.com/GoogleChromeLabs/ProjectVisBug/pull/227

**Comment by dabutvin** [comment]
So the bot has already signed the google CLA, but it is not getting picked up for some reason - see above in this thread.
It seems to work with CLA assistant, but not the google version.

**Comment by mrmajik45** [comment]
Can you sign it on the issue's link? It works.

**Comment by dabutvin** [comment]
@mrmajik45 I did follow the issue link and it is signed, my guess is that there is a problem with the CLA tooling on the google side to read the username from a bot account because it shows something like `imgbot[bot]`

there's a pretty good thread about it here: https://github.com/cla-assistant/cla-assistant/issues/173

**Comment by lorensr** [comment]
@dabutvin  would you mind asking your robot to sign this one as well? 😄

https://cla-assistant.io/temporalio/documentation?pullRequest=1389
