### ISSUE TITLE
making imgbot rescan and update the pr after adding .imbotconfig.

### ISSUE THREAD

**Issue by bonesoul** [dabutvin/ImgBot#180]
so i've have ignored some paths, but i couldn't find a a way to re-trigger imgbot?

**Comment by dabutvin** [comment]
this is a great idea!

over here: https://github.com/dabutvin/ImgBot/blob/master/WebHook/WebHookFunction.cs#L74-L89

We check all the modified and added files to see if there are any images.
We could do an extra check to see if the modified file is `.imgbotconfig`

Then just add a router message if this is the case. Awesome!

**Comment by dabutvin** [comment]
hacktoberfest is over, but this is something we should definitely still do!

**Comment by usmanatron** [comment]
I'm keen to have a go at this!

**Comment by dabutvin** [comment]
Hi @usmanatron 
Go for it!

Comment if you run into any problems getting setup.

Have a look at the test setup at https://github.com/dabutvin/ImgBot/blob/master/Test/WebHookTests.cs
and the mock hooks : https://github.com/dabutvin/ImgBot/tree/master/Test/data/hooks

**Comment by usmanatron** [comment]
Thanks @dabutvin , all makes sense to me.  I've written something which I think will work, just need to run the tests now 🤞

**Comment by dabutvin** [comment]
👍  fixed in #272
