### ISSUE TITLE
Commit message should use imperative mood

### ISSUE THREAD

**Issue by bdougherty** [dabutvin/ImgBot#186]
Using the imperative mood in commit message is a best practice that ImgBot currently doesn't follow (see https://chris.beams.io/posts/git-commit/#imperative).

tl;dr the commit message should be `[ImgBot] Optimize images` instead of `[ImgBot] optimizes images`.

Would be great to change by default, but would be fine to be able to change it as part of the config too.

**Comment by dabutvin** [comment]
👍 Sounds good to me.

I don't think we should make it configurable unless someone really wants to customize it.

**Comment by dabutvin** [comment]
need to update: 

 - https://github.com/dabutvin/ImgBot/blob/master/Test/PullRequestBodyTests.cs
 - https://github.com/dabutvin/ImgBot/blob/master/Common/KnownGitHubs.cs
 - https://github.com/dabutvin/ImgBot/blob/master/OpenPrFunction/PullRequestBody.cs (just a code comment here)

**Comment by dabutvin** [comment]
Fine with me! Go ahead :)

**Comment by mwanchap** [comment]
After much overthinking, I've submitted a PR for this issue - #189

**Comment by dabutvin** [comment]
Quick turnaround! The change is integrated. I'll close this issue when the jobs get deployed

**Comment by dabutvin** [comment]
![image](https://user-images.githubusercontent.com/5168796/46901512-6586fa00-ce6a-11e8-8cb4-6287ad951876.png)

It's live! Thanks all
