### ISSUE TITLE
ImgBot doesn't seem to work properly

### ISSUE THREAD

**Issue by huhuhang** [dabutvin/ImgBot#187]
I have been installing for 1 day and have not received any commits or pr.
I used the default configuration, which is just clicking the install button.

![wx20181012-161645](https://user-images.githubusercontent.com/5147530/46856897-3d7fa280-ce3a-11e8-929a-566ecadde62b.png)

**Comment by dabutvin** [comment]
Hey sorry you're having trouble. I can't keep a look at this for you soon

**Comment by dabutvin** [comment]
I took a look at your compression runs and there are 2 issues at play.

First issue:
 - You are being heavily affected by #170 - we have a plan to fix it if you want to take a look at that issue description. I'm going to take this on ASAP and see if this can clear things up for your repo.

Second issue:
 - A few of your images are throwing  'ImageMagick.MagickCorruptImageErrorException - Unable to decompress the jpeg file.'
- `images\2017\11\-----2017-11-16-09.15.59.jpg`
- `images\2017\11\-----2017-11-16-09.15.59-2.jpg`
- `images\2017\11\-----2017-11-16-09.15.59-1.jpg`

You might want to have a look at those files and see if there is anything obvious about them

I'll reply back here when #170 is resolved and updated and see if that does the trick

Stay tuned!

**Comment by dabutvin** [comment]
We released a fix today and that seemed to work - you should have your optimizations now if you want to confirm everything looks right on your end.

I noticed your repo took a really looooooong time to process and had quite a lot of trouble completing once those initial errors were out of the way.

We are going to have to make some performance improvements soon I think, but I'm going to close this issue in the meantime.

Thanks for opening this here and raising awareness. 👍

**Comment by huhuhang** [comment]
@dabutvin Thank you for your kind help. 🙏
