### ISSUE TITLE
ImageQueryTests: Checks for correct file names should be assertions

### ISSUE THREAD

**Issue by guntbert** [dabutvin/ImgBot#192]
Several tests in ImageQueryTests.cs contain lines after the Asserts that are supposed to check if not only the correct numbers of files have been detected but also the correct files.

        public void GivenDefaultConfiguration_ShouldFindAllImages()
        {
            var images = ImageQuery.FindImages("data", new RepoConfiguration());

            Assert.AreEqual(7, images.Length, $"Images found {string.Join("; ", images)}.");
            images.Contains("a.jpg");
            images.Contains("b.png");
            ...

Currently those lines do nothing, they should be assertions.

**Comment by dabutvin** [comment]
Whoops!

good catch 👍
