### ISSUE TITLE
Read compression settings from config

### ISSUE THREAD

**Issue by squalrus** [dabutvin/ImgBot#2]
Allow consumers to customize:
- filetypes from allowed list http://www.imagemagick.org/script/formats.php#supported
- other options available http://www.imagemagick.org/script/command-line-processing.php#option
- whitelist / blacklist
- timing when bot runs

```json
// .imgbotconfig
{
    "filetypes": ["png", "jpg"],
    "ignoredFiles": ["/img/logo.png", "/img/high-fidelity-images/*.jpg"],
    "schedule": ["1100", "2300"]
}
```

**Comment by dabutvin** [comment]
additional feedback: make it optional to keep images' metadata

**Comment by dabutvin** [comment]
we should add a setting for which branch or branches to work against
see https://github.com/dabutvin/ImgBot/issues/16

**Comment by dabutvin** [comment]
add an option to trim() images
see https://github.com/dlemstra/Magick.NET/blob/master/Tests/Magick.NET.Tests/Shared/MagickImageTests.cs#L3820

**Comment by dabutvin** [comment]
we now have the concept of `.imgbotconfig` 
see https://github.com/dabutvin/ImgBot#configuration

I am going to leave this issue open so we don't lose any of the good suggestions in here. Then open new issues for further config updates

**Comment by dabutvin** [comment]
we have https://github.com/dabutvin/ImgBot/issues/16

I am going to close this one to keep things tidy
