### ISSUE TITLE
Double prs

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#21]
Getting some instances of 2 prs being created for the same branch comparison at the exact same time

We should be able to do something to make sure there's only 1 being made.

**Comment by mxxcon** [comment]
We had this issue with 
https://github.com/2factorauth/twofactorauth/pull/2783 and
https://github.com/2factorauth/twofactorauth/pull/2784

**Comment by dabutvin** [comment]
this is a really annoying issue that is becoming more prominent.  Should definitely get a hold of this problem soon.

Maybe we need to lock across the queueTrigger or add some random delay on the GitHub request...just some thoughts
