### ISSUE TITLE
Installed But No PR

### ISSUE THREAD

**Issue by HDVinnie** [dabutvin/ImgBot#210]
How long does it usually take? Over 24 hours and no PR.

**Comment by dabutvin** [comment]
Hi @HDVinnie thanks for finding your way here! I'm sure we can get this figured out and get those images optimized.

I think you may have missed the last step of getting ImgBot installed into your projects. I see you clicked through the marketplace page, but never configured the app.

Try going to https://github.com/apps/imgbot/installations/new and see if you can choose your repos.
Once you chose where you want to installl, you should start seeing PRs shortly after.

Let me know if you're still having trouble

**Comment by HDVinnie** [comment]
It was installed and repos were chosen. I have uninstalled theft and now reinstalled. Hopefully will see some PR's soon. Thanks.

**Comment by HDVinnie** [comment]
@dabutvin Now seeing the PR's. Thanks.
