### ISSUE TITLE
Config option to auto-merge pull requests

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#231]
- Let users opt into this with a .imgbotconfig setting
 - Require CI to be enabled a green check status before merging
 - maybe add a comment to the PR when it opens that it will be auto-merged if all checks pass?

**Comment by Berkmann18** [comment]
> maybe add a comment to the PR when it opens that it will be auto-merged if all checks pass?

Or have a trigger that enables the bot to do that, say if someone commented "@imgbot merge" which would avoid the situations where some contributors would want to check before it merges but at the same time cut down on the automatable bits of the auto-merging.
