### ISSUE TITLE
unwanted "optimization": removes animation from (a)png's

### ISSUE THREAD

**Issue by jospoortvliet** [dabutvin/ImgBot#256]
Hi,

you do save space if you remove animation frames, but that's typically not wanted ;-)
https://github.com/nextcloud/nextcloud.com/blob/4fc637ccf470691f9b79bcb9453fac52d709ddd4/assets/img/common/yourdata.png animates (in chromium and most other browsers). Yes, that's not how it should be, I should then call it an apng but guess what - that isn't recognized. Browsers somehow deal with animated png's quite well.

See https://github.com/nextcloud/nextcloud.com/pull/1021

**Comment by dabutvin** [comment]
Hey thanks for catching this. Definitely not the intention.

nextcloud continues to find ImgBot problems :) You guys are the best!

**Comment by dlemstra** [comment]
I just pushed a patch to the ImageMagick repository to make it possible to detect if the image is an APNG file. The ImageMagick library currently has no support for this so we should abort the optimization when the file is an APNG file. Will try to publish a new release of Magick.NET next week to fix this. Can I use your image in a unit test @jospoortvliet?

**Comment by dlemstra** [comment]
Decided to use an other image for the unit testing and I will try to publish a new release tomorrow that includes this fix.

**Comment by dabutvin** [comment]
patch applied and verified in a new fork
https://github.com/dabutvin/nextcloud.com/pull/1

thanks all!
