### ISSUE TITLE
Early Adopter Plan

### ISSUE THREAD

**Issue by mrmajik45** [dabutvin/ImgBot#258]
What is the bonus for having the Early Adopter Plan?

**Comment by dabutvin** [comment]
Early Adopter Plan gives you access to use ImgBot on both public and private repos and behaves the same as the premium plan.
See https://github.com/dabutvin/ImgBot/blob/master/WebHook/WebHookFunction.cs#L212-L218 

Early adopter is 781
Premium is 1750

**Comment by mrmajik45** [comment]
Basically just a thank you for being a early user.
