### ISSUE TITLE
Compression not lossless in some cases

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#26]
see https://github.com/facebook/react/pull/10677

The green got a lot lighter in the first image there.

This may be solvable by offering more configuration, or maybe there is some setting we need to set to be closer to truly lossless.

**Comment by mxxcon** [comment]
Perhaps don't recompress jpeg files unless you can ensure that they are 100% lossless?

**Comment by dabutvin** [comment]
There has been some progress on resolving this issue
https://github.com/dlemstra/Magick.NET/issues/124

**Comment by dabutvin** [comment]
fixed in #58. See Magick.NET commit https://github.com/dlemstra/Magick.NET/commit/1725159e6a2ad4dacef4c54bcb7194e6c8b03d17
