### ISSUE TITLE
How to the pull request branch checkout locally?

### ISSUE THREAD

**Issue by johnjohndoe** [dabutvin/ImgBot#265]
I recently added ImgBot to one of my projects. Right after the bot created a new pull request with a few optimized images.
I now would like to checkout the changes locally and at least build and run the project once. I however cannot see how to checkout the pull request branch. There is no forked repository which I could add as an remote via Git.

**Comment by guntbert** [comment]
@johnjohndoe You don't need a **forked** repo, if you have the repo as a remote  this should work (off the top of my head, so be warned :-))
# get all info from remote
    git fetch
# list all branch names
    git branch -a
make the one interesting branch current
    git checkout <name of new branch>

**Comment by johnjohndoe** [comment]
Thanks. I did not realize that the branch is local to my repository.
