### ISSUE TITLE
No pull requests

### ISSUE THREAD

**Issue by gwleuverink** [dabutvin/ImgBot#27]
Hi! I'm trying out ImgBot on a private repository but no pull requests are made by ImgBot. 
ImgBot has been granted all permissions on this repository. Am I missing a step? 

Thanks in advance!

**Comment by dabutvin** [comment]
Hi @gwleuverink thanks for reporting the issue.  
Currently there is no support for private repo
see https://github.com/dabutvin/ImgBot/issues/19

this is a matter of what is probably a simple change to make here: https://github.com/dabutvin/ImgBot/blob/master/ImgBot.Function/CompressImages.cs#L22

using the credentials provider from LibGit https://github.com/libgit2/libgit2sharp/wiki/git-clone

username: "x-access-token" and password from installation token

**Comment by gwleuverink** [comment]
Thanks @dabutvin. Since my issue was a duplicate I'll close it :)
Great idea to integrate image optimisation with GitHub. It will save my a lot of time! Keep up the good work!

**Comment by dabutvin** [comment]
:+1: I released an update to support private repos. You may want to try uninstalling and reinstalling.

If you're still having problems you can always drop a message to imgbothelp@gmail.com and we can get you sorted.

Thank you for the support!

**Comment by gwleuverink** [comment]
It works like a charm after reinstalling! Thanks!
