### ISSUE TITLE
[BUG] Resulting images broken during repo reset

### ISSUE THREAD

**Issue by webknjaz** [dabutvin/ImgBot#273]
I don't know what exactly happened but the resulting images got completely broken in ansible/ansible-lint repo.

Context:
* https://github.com/ansible/ansible-lint/pull/416
* https://github.com/ansible/ansible-lint/issues/435
* https://github.com/ansible/ansible-lint/pull/437

Maybe you could figure out what was that from logs or so.

**Comment by dabutvin** [comment]
Hey thanks for reporting this!

I just forked the project and reproduced the same outcome. Something strange for sure.
https://github.com/dabutvin/ansible-lint/pull/1/files

I wonder if there is a way we can detect this in the code here when it happens or if ImageMagick had any idea it was creating corrupted files.

**Comment by webknjaz** [comment]
Maybe try loosely comparing images?

**Comment by dabutvin** [comment]
I got a chance to debug this further tonight and the result is pretty interesting. The compression of the image is fine, it is the git signature routine that is corrupting the image.

I didn't expect that! 

Here is the relevant code snippet from [the source](https://github.com/dabutvin/ImgBot/blob/master/CompressImagesFunction/CompressImages.cs)

```csharp
var signature = new Signature(KnownGitHubs.ImgBotLogin, KnownGitHubs.ImgBotEmail, DateTimeOffset.Now);
repo.Commit(commitMessage, signature, signature);

// We just made a normal commit, now we are going to capture all the values generated from that commit
// then rewind and make a signed commit
var commitBuffer = Commit.CreateBuffer(
    repo.Head.Tip.Author,
    repo.Head.Tip.Committer,
    repo.Head.Tip.Message,
    repo.Head.Tip.Tree,
    repo.Head.Tip.Parents,
    true,
    null);

var signedCommitData = CommitSignature.Sign(commitBuffer + "\n", parameters.PgpPrivateKeyStream, parameters.PgPPassword);

repo.Reset(ResetMode.Soft, repo.Head.Commits.Skip(1).First().Sha);
var commitToKeep = repo.ObjectDatabase.CreateCommitWithSignature(commitBuffer, signedCommitData);

repo.Refs.UpdateTarget(repo.Refs.Head, commitToKeep);
var branchAgain = Commands.Checkout(repo, KnownGitHubs.BranchName);
repo.Reset(ResetMode.Hard, commitToKeep.Sha);
```


It is the final `repo.Reset` call that is corrupting the images. The images are in good shape every step of the way leading up to that and are fine during the first commit

**Comment by dabutvin** [comment]
@webknjaz thanks for reporting this issue here. Turns out the git compression was the culprit. And while we couldn't find a way to retain the compression without corrupting the images, we do have a safeguard now to stop ImgBot from pushing commits with corrupted images. 

Please feel free to open more issues for any problems or questions you have.
