### ISSUE TITLE
sounds good, does not work

### ISSUE THREAD

**Issue by makc** [dabutvin/ImgBot#30]
![lol](https://m.popkey.co/c5fee4/RZ1ZL.gif)

repository size actually grows by the size of images you change minus your 'saved space', because old images are not going anywhere from git history.

**Comment by dabutvin** [comment]
I understand the concern about your git repo's growing in size, I too hate every second waiting to clone.
And if this is your primary concern, then this app is probably not for you.

However, a lot of projects on GitHub are developed and then released (i.e. a website or a mobile app, etc)

These releases do not include the git history, they take the images in their current state and package them up or push them to a server.

It is for these releases that the space is saved.  

So when a customer visits your app or website or whatever you release, they can download less bits.

Does this make sense?

**Comment by makc** [comment]
isn't it good idea to do that in deploy script

**Comment by mlissner** [comment]
I suggest closing this issue. This tool isn't about making repos smaller. It's about making the latest commit smaller.

> isn't it good idea to do that in deploy script

Sure, but this is one click and setting up configuring a deploy script (and managing compression libs and whatnot) is hard.

**Comment by makc** [comment]
N/p, it's not like I am waiting for them to fix  it.
