### ISSUE TITLE
update website to state optimization method

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#31]
people want to know

 - What tools do you use to optimize?
- explicitly state if you optimize images using lossless or lossy methods.

**Comment by mlissner** [comment]
Came here to write exactly this. I just got my first PR, and it *looks* OK in Github, but I'd love to know the details.

This is also helpful in my own optimization routines. If we're using the same thing, I'll stop bothering. If you're using something different, I'll probably continue using my method.

**Comment by dabutvin** [comment]
https://imgbot.net/docs

![image](https://user-images.githubusercontent.com/5168796/32428138-2232b49a-c279-11e7-97d2-4f9cb9fe83c8.png)
