### ISSUE TITLE
Organization repositories aren't recognized ?

### ISSUE THREAD

**Issue by mulle-nat** [dabutvin/ImgBot#328]
The organization repositories aren't listed in the available repositories and I think there is no way to add an app to an organizatio. This means that organization repositories can't be optimized.

**Comment by dabutvin** [comment]
Hi @mulle-nat you should be able to install into any organization you have rights on.

Try going to https://github.com/marketplace/imgbot/#pricing-and-setup and choosing the Account dropdown
Also check out https://github.com/apps/imgbot/installations/new to see what organizations show up there.

Can you share what you see?

**Comment by mulle-nat** [comment]
Nice the second link it what I was searching for, but couldn't find . Thx.
