### ISSUE TITLE
Signoff commit to agree with DCO

### ISSUE THREAD

**Issue by iamsauravsharma** [dabutvin/ImgBot#348]
ImgBot should signoff commit so it agrees with [DCO](http://developercertificate.org/) default ```git commit -s``` or ```git commit --signoff``` command

**Comment by SuperSandro2000** [comment]
The thing you wanted to link is broken.

And I think this is a good idea.

**Comment by dabutvin** [comment]
Hi @iamsauravsharma @SuperSandro2000 Thanks for raising this!

I'm not too familiar with the signoff.
ImgBot already does a GPG signature on every commit. I'm curious, why would you want a signoff in addition to a signature?

**Comment by SuperSandro2000** [comment]
I hope this short StackOverflow helps you https://stackoverflow.com/a/1962112/4446318
Basically it says that the commit is done by ImgBot in case you create a patch from it and git author and commiter gets lost by that.

**Comment by dabutvin** [comment]
sweet. Thanks for the link.

It looks like we can add this at the end of the commit message body.
It is not a header or anything fancy, so if that is the case it should be pretty trivial.

Should it always be ImgBot signing off on the commit? Or should it be configurable, that the person that installed the bot can say they sign off on it?

```
$"Signed-off-by: {KnownGitHubs.ImgBotLogin} <{KnownGitHubs.ImgBotEmail}>"
```

Add the line here: https://github.com/dabutvin/ImgBot/blob/master/CompressImagesFunction/CommitMessage.cs#L50

update the tests here: 
https://github.com/dabutvin/ImgBot/blob/master/Test/CommitMessageTests.cs

Up for grabs if anyone wants to take it on

**Comment by SuperSandro2000** [comment]
I don't see a reason not to. Maybe make it opt-out if someone is annoyed by it.

**Comment by dabutvin** [comment]
For one of your projects, like https://github.com/SuperSandro2000/Space-Station/pull/1 would you configure it to say you sign off?

```
[ImgBot] Optimize images

*Total -- 5,527.24kb -> 4,395.47kb (20.48%)

/graphics/deepwater/deepwater-outer-corner.png -- 14.72kb -> 0.56kb (96.18%)
/graphics/deepwater/deepwater-side.png -- 14.99kb -> 0.71kb (95.26%)

Signed-off-by: SuperSandro2000 <sandro.jaeckel@gmail.com>
```

Or would you rather see it be signed off by ImgBot?


```
[ImgBot] Optimize images

*Total -- 5,527.24kb -> 4,395.47kb (20.48%)

/graphics/deepwater/deepwater-outer-corner.png -- 14.72kb -> 0.56kb (96.18%)
/graphics/deepwater/deepwater-side.png -- 14.99kb -> 0.71kb (95.26%)

Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>
```

**Comment by SuperSandro2000** [comment]
That's a good question. My intuition says signed off by imgbot cause I didn't do anything.

**Comment by dabutvin** [comment]
looks like for things like probot/dco they require the commit author match the email that is in the Signed-off-by

https://github.com/probot/dco/blob/master/lib/dco.js#L53-L56

**Comment by dabutvin** [comment]
let's do this ! you can see dependabot does it
![image](https://user-images.githubusercontent.com/5168796/60906864-043f5c00-a22d-11e9-8748-4b94c91c2c0c.png)

who wants it!??

**Comment by dabutvin** [comment]
opened #445 to add this to the commit message
