### ISSUE TITLE
Rebasing a PR from ImgBot

### ISSUE THREAD

**Issue by kolappannathan** [dabutvin/Imgbot#352]
I recently encountered a conflict in a PR in my fork repo due to a change in base repo. It could be really nice to have a rebase feature in PR.

Something along the lines of how Dependdabot does it now. For example, the following comment in a existing PR might trigger a rebase and ImgBot will compress the images again, force push new changes to the PR.

`@ImgBotApp rebase`

**Comment by dabutvin** [comment]
this is a great idea. Dependabot is awesome!

Right now the work around is to delete the branch and then trigger a new optimization run through https://imgbot.net/app but this is certainly not ideal.

I wonder if we could do a rebase automatically if there is conflicts so it just happens - I've seen dependabot do that when I bring in multiple updates one after the other that conflict

**Comment by kolappannathan** [comment]
@dabutvin The word around you suggested got the job done for now. Thanks.

**Comment by kolappannathan** [comment]
Kindly don't close this.

**Comment by Munyola** [comment]
Yes that bot is active,keep up i like it📡

**Comment by dabutvin** [comment]
This would be really cool to do, I wonder what kind of permissions change we would need.

I'm also wondering if we can do this with the new GitHub actions recently announced

**Comment by javierron** [comment]
Hello!

Me and @s1grun will like to implement this feature. Is there something important we should know before getting started?

**Comment by dabutvin** [comment]
Awesome! Checkout https://imgbot.net/docs/#contributing for some pointers on getting started running the bot locally.

Let me know if I can help

**Comment by dabutvin** [comment]
fixed in #635

When images are added or modified with an existing branch we will not update the existing PR.

Thanks @javierron and @s1grun 🎉 
Working great in production.
