### ISSUE TITLE
ImgBot does not run when requested

### ISSUE THREAD

**Issue by thomasttvo** [dabutvin/ImgBot#367]
How to reproduce:
1/ First install, worked fine - ImgBot created a PR
2/ Closed the PR (I did this because we had another big release that gets merged right afterwards making this PR obsolete)
3/ Try to request ImgBot to run again via imgbot.net/app
4/ No PR created over the past 11 hours even though the /app site says "The last optimization request was sent 11 hours ago"

**Comment by dabutvin** [comment]
Hi @thomasttvo thanks for the detailed repro steps. Super helpful!

Can you check to see if the branch named `imgbot` was deleted when you closed the PR?
That is the most common case of getting in this situation.

If it was left open, can you delete the branch and then request ImgBot to run again?

Whenever the branch is left open, ImgBot doesn't run on your repo, when the branch is deleted, ImgBot regularly checks to see if there are any new images to optimize on an ongoing basis.

Let me know if this works for you
Thanks for supporting ImgBot 😎

**Comment by thomasttvo** [comment]
Ha! I have not deleted it. Shouldn't instruction be included in the PR message: "Your image file size has been reduced by x% "? Like "Don't forget to delete the branch"

**Comment by dabutvin** [comment]
I really like that idea!

Something like, "If you don't want this PR right now, feel free to close. If you want more optimizations later, make sure to delete the branch named 'imgbot' and we'll make a new pr"

**Comment by thomasttvo** [comment]
If I do merge without deleting the branch, ImgBot still won't run again, right? 
Perhaps this additional message should stay true regardless of whether I'm closing or merging.

**Comment by dabutvin** [comment]
Yes, I agree, we should make the wording so it covers both cases.

In most cases when the PR is merged into the default branch and it hasn't been modified, ImgBot will delete the branch on your behalf shortly after merging.

**Comment by thomasttvo** [comment]
Oh, now I can understand the complex scenarios behind this, but perhaps making the wording cover both cases would still be the simplest solution.

**Comment by thomasttvo** [comment]
> Btw. I've just requested another optimization. Will let you know in a few hours

It worked!

**Comment by dabutvin** [comment]
great! I opened #369 to follow up on the messaging updates in the pr body.

thanks again!

**Comment by Maskedman99** [comment]
I was wondering why imgbot didn't make a PR again after closing a PR.
Would be nice if this is mentioned in the README file.
