### ISSUE TITLE
Does ImgBot only interact with the default branch?

### ISSUE THREAD

**Issue by williamli** [dabutvin/ImgBot#435]
Does ImgBot only interact with the default branch?

I use `dev` branch for development and would like to get ImgBot to look for new images there so I can compress images during the development flow instead of doing it after everything is merged into production at default `master` branch.

**Comment by RenanMsV** [comment]
Yes and its being discussed at #155

**Comment by dabutvin** [comment]
thanks, yep that looks like the right issue to track this. I'll comment there now.

**Comment by Remzi1993** [comment]
@williamli Unfortunately, it seems that way.

**Comment by dabutvin** [comment]
👍

**Comment by dabutvin** [comment]
The fix for this is now live in production. You can update your setting by logging into https://imgbot.net/app and hitting the gear icon on your repo's card.

Please reach out if you run into any problems
