### ISSUE TITLE
Add totals/averages to the commit message

### ISSUE THREAD

**Issue by mlissner** [dabutvin/ImgBot#46]
I wanted to brag for you on Twitter with something like:

> On average it compressed our images xx%!

But I don't know the number. Would be great to include this.

**Comment by squalrus** [comment]
Love the idea!

I feel totals would be more impactful, "ImgBot™ saved me 156kb across 28 images!"

Averages could mean different things -- 50% from a 2kb image is a lot different than 1% of a 6MB image.

**Comment by mlissner** [comment]
That works too, though I'm comfy with average compression percentages too.

**Comment by mlissner** [comment]
Beautiful! Thank you for this wonderful tool.
