### ISSUE TITLE
Running ImgBot in repo wiki

### ISSUE THREAD

**Issue by RoiArthurB** [dabutvin/Imgbot#461]
Hello,

I was wondering if it's possible to run ImgBot in a wiki? Actually, I'm part of a [quite big project](/gama-platform/gama) with a consequent wiki in the main repo (the wiki folder is more than 600Mo !).

So, to light up the wiki, I would like to run ImgBot which is already installed in the repo for the code side of the project :smile:  

I don't know if it's possible, if you're currently working on it nor anything.. So I'm waiting for your reply to see what I can do :wink: 

Regards

**Comment by dabutvin** [comment]
Hey @RoiArthurB ! Great question, I love this idea.
We should be able to clone and work on the wiki just like any other repo.

However, since only the master branch shows up and there is no pull request flow, I wonder if imgbot would probably have to push directly to the master branch.

https://help.github.com/en/articles/adding-or-editing-wiki-pages

**Comment by RoiArthurB** [comment]
I agree that technically, it's not harder to run ImgBot on a wiki than on a repo, but you're right: how to do pull request...

Actually I see 2 solutions: 
1) IB can simply directly push on the master branch and that's all
2) IB can work on another branch where it can do all it changes and after (in command line) do the merge manually! 
But the problem is that noone will be informed of the IB pull request (or that the bot did the job)...

**Comment by RoiArthurB** [comment]
Hello,

Sorry to up this issue but I'd like to know if you're working on it, if you had some new ideas or if you won't work on it because it's impossible on GitHub to create some PR for the wiki ?

Thanks in advance :smiley:

**Comment by dabutvin** [comment]
Hi @RoiArthurB 

No worries :) thanks for following up.

Given the nature of the wiki I think anything more complicated than just pushing to the master branch would be overkill.

Let's enable this with a setting like, `compressWiki = true` and then just regularly push to master branch of the wiki repo when we can.

**Comment by dabutvin** [comment]
here is a rough outline of the work required.
These can be split into multiple PRs if desired too 👍 

## Implementation

- update [RepoConfiguration](https://github.com/dabutvin/ImgBot/blob/master/Common/RepoConfiguration.cs) model to add this new property
- Add new condition around [here](https://github.com/dabutvin/ImgBot/blob/b1d8f3dea2e9ca24ca7e55a0c9bc5056a01dd5fd/CompressImagesFunction/CompressImages.cs#L79) that checks if CompressWiki is true
- if it is true, we need to create a new `CompressImagesMessage` instance and set the `CloneUrl` to this pattern `https://github.com/YOUR_USERNAME/YOUR_REPOSITORY.wiki.gi`
- once you have that instance we need to drop it into the `compressimagesmessage` queue similar to how we queue messages to the `openprmessage` queue, with an `ICollector`

## Documentation:

- update [Readme](https://github.com/dabutvin/ImgBot/blob/master/README.md) to show config options
- update [configuration doc](https://github.com/dabutvin/ImgBot/blob/master/Docs/configuration.md) for website
- add new doc in [this folder](https://github.com/dabutvin/ImgBot/tree/master/Docs) called compress-wiki.md to explain what this setting does
- update doc [metadata.json](https://github.com/dabutvin/ImgBot/blob/39e0e7f8971181ea94d3cc70f075d51605dfa5ed/Web/src/docs/metadata.json) to include this new doc

**Comment by ElSiipo** [comment]
Currently looking into this one.

Is it a good approach to create a new queue, like this one:
`[Queue("longrunningcompressmessage")] ICollector<CompressImagesMessage> longRunningCompressMessages`

And then have a new function like `LongCompressImagesFunction` ?

**Comment by dabutvin** [comment]
I was thinking we could use the very same queues that currently exist, updating the cloneUrl property to do different behavior. Would need to work out of the master branch in this case as well.

If you get in there and it feels like a new queue makes more sense, then please go for it :)

**Comment by dabutvin** [comment]
fixed in #506 

The history only seems to show up on the git command line, but this can be enabled with `.imgbotconfig`
