### ISSUE TITLE
Update github actions workflow to the new format

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#486]
we have the original format in the .github folder here, but it should be in yaml now.

There's a project to help migrate too!

https://github.com/actions/migrate

The only thing we use actions for is to publish the compressor image to docker hub

**Comment by tjrobinson** [comment]
@dabutvin I'd be happy to give this a go for #hacktoberfest

**Comment by tjrobinson** [comment]
@chekkan You beat me to it :) I'll see if there's anything else I can help with.

**Comment by dabutvin** [comment]
Ahhh.

Let me know what stands out to you and we can work through it together 🤸
