### ISSUE TITLE
add support for mozJpeg compression 📸

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/Imgbot#488]
see 
https://github.com/mozilla/mozjpeg
https://imagecompressor.io/blog/mozjpeg-guide/

At first glance, it looks like we can use 
cjpeg = lossy.
jpegtran = lossless.

We should do a good job picking out appropriate default arguments - we can provide configuration options to users if that makes sense too

new file called `MozJpegCompress.cs` and implement the 3 functions

```cs
namespace CompressImagesFunction.Compressors
{
    public class MozJpegCompress : ICompress
    {
        public string[] SupportedExtensions => new[] { ".XXX", ".YYY" };

        public void LosslessCompress(string path)
        {
            throw new System.NotImplementedException();
        }

        public void LossyCompress(string path)
        {
            throw new System.NotImplementedException();
        }
    }
}

```

see [SvgoCompress](https://github.com/dabutvin/ImgBot/blob/master/CompressImagesFunction/Compressors/SvgoCompress.cs) for a guide of how to shell out and set up arguments

Register the new compressor so we start picking it up at the top of [CompressImages.cs](https://github.com/dabutvin/ImgBot/blob/master/CompressImagesFunction/CompressImages.cs)

Update the [Dockerfile.CompressImages](https://github.com/dabutvin/ImgBot/blob/master/Dockerfile.CompressImages) file to properly install the library on the container image

**Comment by TPS** [comment]
1 note: Per https://imagecompressor.io/blog/mozjpeg-guide/,
> **tip:** run lossless compression after lossy for best results.

Maybe make this default behavior after _every_ lossy operation, whatever is part of the particular toolchain (per options)?

**Comment by dabutvin** [comment]
merged in #495

**Comment by dabutvin** [comment]
we should probably take a pass through the Docs folder and see if we should update anything before we do a new release

**Comment by dabutvin** [comment]
This is all wrapped up and released 👍 👍 👍

**Comment by ElSiipo** [comment]
This feels fantastic!
Big thanks is for your support! :-)

Den fre 18 okt. 2019 19:36Dan Butvinik <notifications@github.com> skrev:
