### ISSUE TITLE
Support alternate locations for .imgbotconfig

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#49]
see https://github.com/facebook/react-native/pull/16591#issuecomment-340801674

today we are pinned to the root of the repo, but there's no reason we can't look in other places.

**Comment by mlissner** [comment]
Seems fine to me. Does Travis support this?

**Comment by dabutvin** [comment]
I don't think Travis will let you put your config anywhere else but root.

The contributing.md as an example can go in root, docs, or .github folder.

As people use more and more bots I think a bots folder or something like that will become more prevalent.

I don't see this as a high priority item, but a relatively simple one - especially for a first time contributor.

**Comment by dabutvin** [comment]
I'm inclined to agree with you :)

**Comment by 895aungye** [comment]
09791831906

**Comment by Thezone1975** [comment]
;)

**Comment by da748** [comment]
Less go there
