### ISSUE TITLE
svg files ignored in `ignoreFiles` config

### ISSUE THREAD

**Issue by Cherry** [dabutvin/Imgbot#491]
It appears that since SVG optimisation was added in https://github.com/dabutvin/ImgBot/pull/386, we're unable to disable SVG optimisation from occurring in our repo.

Our `.imgbotconfig` currently looks like:
```json
{
	"ignoredFiles": [
		"assets/svg/*",
		"assets/svg*",
		"*.svg"
	],
	"aggressiveCompression": false
}

```
(you can see the various options we tried), with the paths of our SVGs from the root being:
- `assets/svg/players.svg`
- `assets/svg/power.svg`
etc.

We have our own build chain for SVGs as we have very specific SVGO options we apply to each of them, but no matter what we set, it appears the SVG optimization seems to always run.

**Comment by dabutvin** [comment]
Thanks for reporting this!

I'll have a look right away

**Comment by dabutvin** [comment]
I just ran a test with a `.imgbotconfig` that looks like this and it successfully ignored svgs in the root and in a nested folder.
https://github.com/dabutvin/test/blob/master/.imgbotconfig

Can you have a quick peek at your config file see if you notice any difference between yours and mine from this test?

**Comment by Cherry** [comment]
Hmm, thanks for taking a look. I just edited our `.imgbotconfig` to only have `*.svg` in the `ignoreFiles` array and it's working now. I'll have to do some more testing with the path options to see if those are an issue.

**Comment by dabutvin** [comment]
Interesting. Glad to hear you are unblocked! 

The way the image query works is, first we find all the image files and then each entry in the ignoredFiles pattern list is evaluated one by one to filter out images from the list. They are never additive, so it would be strange to have any other entries in there cause this kind of side affect.

Definitely feel free to reach out if anything else comes up.

**Comment by igorkulman** [comment]
Having the same problem with SVG files. My [config ](https://github.com/igorkulman/coding-journal/blob/master/.imgbotconfig) says

```
"ignoredFiles": [
    "themes/beautifulhugo/static/fontawesome/webfonts/*"
]
```

But I just got a [PR](https://github.com/igorkulman/coding-journal/pull/54/) optimizing SVG files at that path.

**Comment by dabutvin** [comment]
Hi @igorkulman !

Don't forget to add the curly braces around the property to form a full json object. Let me know if that works :1st_place_medal:
