### ISSUE TITLE
Add option for ImgBot to select which branch to watch (and request PR's against)

### ISSUE THREAD

**Issue by WouterVdS** [dabutvin/Imgbot#505]
By default, ImgBot checks the repository's default branch. But it would be nice if that was configurable, so pull requests could come in a development branch for example before going into master.

**Comment by dabutvin** [comment]
Hi @WouterVdS thanks for dropping by!

This is one of our most requested features right now and the development is already started in #497 

The reason this setting has to be outside of `.imgbotconfig` is that file lives within a branch. You can see the full discussion at #155

Let me know if you want to help out or anything else comes up.
Stay tuned for updates!

**Comment by WouterVdS** [comment]
Sorry! I didn't immediately found the open issue regarding this!

**Comment by dabutvin** [comment]
This is now live in production. You can update your setting by logging into https://imgbot.net/app and hitting the gear icon on your repo's card.

Please reach out if you run into any problems

**Comment by WouterVdS** [comment]
Works like a charm!
