### ISSUE TITLE
Add Docker file validation on PRs

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/Imgbot#519]
We should use github actions for this. We are building and running tests on appveyor right now on PRs, but this does not include the docker file.

I think eventually we should move everything to github actions, but this would be a good start and give us extra coverage.

I just want to make sure whatever changes are made still let the compression container build so something like this should work

```
$ docker build -f Dockerfile.CompressImages . -t imgbot
```

**Comment by Maruda1986** [comment]
> We should use github actions for this. We are building and running tests on appveyor right now on PRs, but this does not include the docker file.
> 
> I think eventually we should move everything to github actions, but this would be a good start and give us extra coverage.
> 
> I just want to make sure whatever changes are made still let the compression container build so something like this should work
> 
> ```
> $ docker build -f Dockerfile.CompressImages . -t imgbot
> ```

**Comment by dabutvin** [comment]
bump

**Comment by dabutvin** [comment]
Bump
