### ISSUE TITLE
Auto-merge Imgbot to non-master branch

### ISSUE THREAD

**Issue by lovincyrus** [dabutvin/Imgbot#532]
Attempted to auto-merge Imgbot pull request into `staging` using `Mergify`. But, Imgbot only opens pull requests with `master`. According to https://github.com/dabutvin/Imgbot#configuration, there is no way to open pull requests and select branches to auto-merge with, or is there?

Reference: https://github.com/lovincyrus/cosmonauts-world/issues/28

**Comment by dabutvin** [comment]
Hi @lovincyrus thanks for opening an issue!

We recently added support for changing the default branch in https://github.com/dabutvin/Imgbot/pull/497

Let me know if this works for you. Thanks 😊

**Comment by lovincyrus** [comment]
> Hi @lovincyrus thanks for opening an issue!
> 
> We recently added support for changing the default branch in #497
> 
> Let me know if this works for you. Thanks 😊

Sick! Thanks for the reply. I should've checked the Imgbot dashboard. How long will it take effect after requesting the new default branch changes?
