### ISSUE TITLE
Add support for svg files

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#56]

**Comment by dlemstra** [comment]
Maybe we could add this to Magick.NET? Would like to know what are your plans for this? Just remove white space?

**Comment by dabutvin** [comment]
That would really cool to add an SVG Optimizer to Magick.NET!

I was looking at https://github.com/svg/svgo and it looks really promising
I think there are some defaults like removing whitespace and minifying styles that we could flip on to start getting SVG files in the mix and then offer some options for more optimization down the road.

Once the basic support is working we could allow users to do more advanced things to set allowed attributes and strip height/width etc

**Comment by nikolenkoanton92** [comment]
@dabutvin https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.NodeServices#microsoftaspnetcorenodeservices

**Comment by nikolenkoanton92** [comment]
https://github.com/svg/svgo

**Comment by dlemstra** [comment]
Can you explain what you mean with this link?
