### ISSUE TITLE
Can't Add ImageBot to a Repo I am an admin for

### ISSUE THREAD

**Issue by melloware** [dabutvin/ImgBot#57]
I am a member of the PrimeFaces Extensions team and I want to add ImgBot to our showcase webapp project here:

https://github.com/primefaces-extensions/showcase

But your selection option to start ImgBot is only showing me my personal and forked repos.  How can I add the above to ImgBot?

**Comment by dabutvin** [comment]
hi @melloware you need to be an owner or admin of the organization to install apps.

Can you check your role?

Either way, I contacted GitHub support to get this sorted out.

Thanks!

**Comment by melloware** [comment]
Thanks for looking into this.  And also AWESOME project!  It not only showcases cool use of technology but its making the world a better place by reducing bandwidth!

Here is a screenshot showing I am listed as an Admin...

![image](https://user-images.githubusercontent.com/4399574/32547806-b3ff39e6-c451-11e7-8517-c4142a18fda6.png)

**Comment by dabutvin** [comment]
I got a response from GitHub - they suggested that you post in the forums for support at https://platform.github.community/c/integrations

I looked around and found the following posts that may help.

 - https://platform.github.community/t/why-cant-repository-admins-install-integrations-in-their-repository/882/12
 - https://platform.github.community/t/adding-an-integration-when-not-an-admin/1509/10

can you post a screenshot of what you are seeing? That may help.

It definitely seems like they want repo-admins to be able to add integrations.

what do you see when you go to https://github.com/apps/imgbot/installations/new ??

**Comment by melloware** [comment]
I just see this and when I pick select a repository only my personal repositories are listed.

![image](https://user-images.githubusercontent.com/4399574/32726360-bb7ca69c-c846-11e7-9ca1-ef8c67c010cc.png)

**Comment by melloware** [comment]
for now I just forked my project.  Added imgBot and it optimized the images and then I pushed that PR back to my main project.  So I accomplished my main goal of optimizing images it just won't be done on an  ongoing way.

**Comment by dabutvin** [comment]
Glad you found a work around.
GitHub apps are still fairly new. I'll keep an eye out for any more information on this kind of thing
