### ISSUE TITLE
Option to Auto Merge PRs or Commit to Master

### ISSUE THREAD

**Issue by Matt-Gleich** [dabutvin/Imgbot#600]
I have a project where I am always adding new images. It would be great if I could define in the imgbot config file if imgbot should make a pr or commit right to master

**Comment by dabutvin** [comment]
we looked at auto-merging the PR a while back in #231 but never got it together.
I think it would be great to expand the options here.

There are some existing workarounds that I have seen people use
here is an example using github action https://github.com/marketplace/actions/pr-merge-bot
https://github.com/Synixe/Documents/blob/master/.github/workflows/imgbot.yml
