### ISSUE TITLE
Option to aggressively compress some images, losslessly compress others?

### ISSUE THREAD

**Issue by justingolden21** [dabutvin/Imgbot#625]
According to the [docs](https://imgbot.net/docs/), it seems we can set it to aggressively compress: `'aggressiveCompression': true`, and we can ignore files: 

```
"ignoredFiles": [
        "*.jpg",                   // ignore by extension
        "image1.png",              // ignore by filename
        "public/special_images/*", // ignore by folderpath
    ],
```

But what if we want to aggressively compress some images, while still being able to losslessly compress others?

Feel free to tell me if I'm wrong and there is already a way to do this, I looked through the docs and can't find it. Thank you for making Imgbot so awesome :)

**Comment by dabutvin** [comment]
hi @justingolden21 great idea!

This is not currently possible, but combining some of what we have for ignoring files by path and the existing aggressiveCompression should make this possible.

**Comment by justingolden21** [comment]
Thank you for your quick reply.

This is true that it's possible, albeit with two steps. We first have to ignore the files we want to losslessly compress and set aggressiveCompression to true, then wait for imgBot to make a merge request and merge, then finally change the settings to lossless compression and invert (or possibly set to none?) the ignored files.

In a large scale project, every single time we modify images and want to compress them, we must go through these steps, which is the purpose Imgbot seems to serve (making it thoughtless and effortless to maintain compressed images in one's repo). Now of course we could do this only when we need the images compressed; it doesn't need to be done every commit, or even every commit with images. But still, I think this functionality, however niche, would be useful for more than just a handful of users.

**Comment by dabutvin** [comment]
Totally agree. We should let you turn on aggressive compression on a subset of files.

**Comment by justingolden21** [comment]
Just commenting to see if anybody is still looking into this, and to see if the bot will mark it as "unstale" if it has activity. I still think this is a useful feature for ImgBot.

Thanks again.

**Comment by dabutvin** [comment]
Bump
