### ISSUE TITLE
Build trigger?

### ISSUE THREAD

**Issue by daveabrock** [dabutvin/Imgbot#640]
Thanks for your work on this—I just discovered this and I love it for my GitHub pages blog. Apologies if I didn't see this in an issue or the docs, but I don't see it anywhere.

Say, would there be any "on demand" triggers that might facilitate running this as part of a build process?

**Comment by dabutvin** [comment]
Hi @daveabrock!

Tell me more about how you see this integrated in your build. You want a build to trigger a PR? Or you want to skip checking in the compression result and just apply to your build output?

We do have an on demand trigger from the website at https://imgbot.net/app/ that you could check out

**Comment by daveabrock** [comment]
Saw the app, @dabutvin, and thanks!

I am getting started with GitHub Actions, and I was thinking about having it as something done as part of a merge and not after.

**Comment by daveabrock** [comment]
Thanks for the response, this can be closed.
