### ISSUE TITLE
expand Gif Image files support

### ISSUE THREAD

**Issue by Davoleo** [dabutvin/Imgbot#644]
Gifs usually take up a lot of space, it'd be nice if img-bot could do some optimizations to reduce their file size

Possible reference: #332

**Comment by dabutvin** [comment]
we do optimize gifs today using Image Magick gif optimizer https://github.com/dlemstra/Magick.NET/blob/master/src/Magick.NET/Shared/Optimizers/GifOptimizer.cs
 
I could however see us implementing something additional like gifsicle to do even more
https://packages.debian.org/unstable/graphics/gifsicle

**Comment by Davoleo** [comment]
umh, then I wonder why it didn't try to optimize gifs in this PR: https://github.com/Davoleo/davoleo.github.io/pull/5 🤔 
is it disabled by default?

**Comment by dabutvin** [comment]
Hi @Davoleo 
Gif optimization is enabled by default.
I just took a look at the logs for that compression run and it did try to optimize that gif, but found no space savings. I'm going to try again with gifsicle and see if that can do anything further

**Comment by dabutvin** [comment]
added support for gifsicle in #654 

@Davoleo I forked your example project to try it out on.

This is with the default settings: https://github.com/dabutvin/davoleo.github.io/pull/1

This is with the opt in to aggressive compresion: https://github.com/dabutvin/davoleo.github.io/pull/2

**Comment by Davoleo** [comment]
oh I see, thanks for the help

**Comment by dabutvin** [comment]
released in [1.11.0](https://github.com/dabutvin/Imgbot/releases/tag/1.11.0)
