### ISSUE TITLE
ImgBot doesn't optimizes all repo's images

### ISSUE THREAD

**Issue by Panquesito7** [dabutvin/Imgbot#650]
`ImgBot` doesn't optimizes images in other folders.
Is this normal, or is there an option for this?

**Comment by dabutvin** [comment]
hi @Panquesito7 👋 

Imgbot does recursively search all folders in the repo for images to optimize.

It's possible that the images in the folders were already optimized. Did you get any pull request at all? Can you share a link to the repo you were wondering about and I can take a look closer.

**Comment by Panquesito7** [comment]
> Did you get any pull request at all?

Yes, I've received PR, but it only optimized one screenshot.

> Can you share a link to the repo

Yes, here it is: https://github.com/Panquesito7/cloud_items

**Comment by dabutvin** [comment]
thanks @Panquesito7 

I just took a look at the logs and looks like everything ran fine and only the 1 image had any room for lossless compression.

If you want to save more space, you could opt in to the more aggressive optimization scheme, https://imgbot.net/docs/#aggressive-compression

**Comment by Panquesito7** [comment]
Thanks for the assistance, @dabutvin! 🙂
Closing this issue.
