### ISSUE TITLE
SVG colors turn to black when classes begin with numbers

### ISSUE THREAD

**Issue by chrisblakley** [dabutvin/Imgbot#666]
This might be an issue with SVGO because I noticed the same thing on another tool (and I'm guessing Imgbot must use that or handle SVGs similarly).

Adobe Illustrator generates random class names for paths in SVGs (like `02d93889-0fb2-45e9-aa3c-bfb1baf7f55e`), but unfortunately sometimes those class names start with numbers. When that happens, Illustrator escapes and _encodes(?)_ the first character in the `<style>` tag like this: `.\30 2d93889-0fb2-45e9-aa3c-bfb1baf7f55e {fill: #9fa1a4;}`

The escaped character always seems to be a `\3`... and it always adds a space after the real number, so if the class started with a `4` it would escape as `.\34 ` and if it were a `3` it would escape it as `.\33 ` etc.

Now the problem is that Imgbot wants to either remove the style tag completely, or minify the style tag. Either way, this causes any styles to not get inlined to that path and instead are just removed entirely. I notice this because certain elements turn to black from whatever color they used to be.

The real solution for this would be to have Illustrator (or any program) begin all generated classes and IDs with letters, but we can't expect that to happen, so instead Imgbot should try to better associate these escaped class selectors to their appropriate target.

Here is an example file. Notice the "Group" path has a class that begins with a number and so if it is run through Imgbot that word will change to black.

```svg
<svg xmlns="http://www.w3.org/2000/svg" id="04c010dd-b0ff-4934-bf2b-f6bb34804e60" data-name="Layer 1" viewBox="0 0 225 22.75">
	<defs>
		<style>
			.e773c100-103b-45a6-8f1d-e8b913541c50 {fill: #0099d8;}
			.b92747d9-14c1-46ff-8b3c-6d7694c1731c {fill: #0093d0;}
			.e7849aa7-b960-44b2-b1bf-8cd6bddf76bd {fill: #a0cf67;}
			.\30 2d93889-0fb2-45e9-aa3c-bfb1baf7f55e {fill: #9fa1a4;}
		</style>
	</defs>
	<path d="M.88 16.3l1.79-4.77h5.16L6 16.3H.88m7.57 0l1.79-4.77h5.16l-1.79 4.77H8.44m2.67-7l1.79-4.77h5.16l-1.78 4.81h-5.17" class="e773c100-103b-45a6-8f1d-e8b913541c50"/>
	<path d="M21.46 1.47H27c4.06 0 5.09 2.28 5.08 4.15s-1 4.15-5.09 4.15H23.6v6.53h-2.16V1.47zM23.6 8h2.82c1.7 0 3.41-.38 3.41-2.39s-1.7-2.39-3.4-2.39h-2.82V8zm11.46-6.57a1.44 1.44 0 0 1 1.48 1.38 1.48 1.48 0 0 1-3 0 1.45 1.45 0 0 1 1.52-1.38zM34 6.37h2v9.93h-2V6.37zm4.89 0h2V7.9a3.8 3.8 0 0 1 3.5-1.78 3.54 3.54 0 0 1 3.85 3.79v6.39h-2v-5.87a2.27 2.27 0 0 0-2.42-2.55c-1.68 0-3 1-3 3.31v5.11h-2V6.37zM58.66 9A3.48 3.48 0 0 0 56 7.9a3.25 3.25 0 0 0-3.32 3.52 3.28 3.28 0 0 0 3.43 3.37 3.25 3.25 0 0 0 2.58-1.11L60.13 15a5.43 5.43 0 0 1-4 1.53c-3.27 0-5.56-2.12-5.55-5.17s2.25-5.23 5.56-5.23a5.64 5.64 0 0 1 4.08 1.57L58.66 9zM61.54.46h2v10.22l4.58-4.29h2.8l-5 4.5 5.37 5.4h-2.82l-4.93-5.15v5.16h-2V.47zm11.29 5.9h2V7.9a3.8 3.8 0 0 1 3.5-1.78 3.54 3.54 0 0 1 3.85 3.79v6.39h-2v-5.87a2.27 2.27 0 0 0-2.38-2.55c-1.68 0-3 1-3 3.31v5.11h-2V6.37zM86.47 12c0 1.74 1.72 2.89 3.58 2.89A3.74 3.74 0 0 0 93 13.43l1.52 1.09a5.73 5.73 0 0 1-4.71 2 5.1 5.1 0 0 1-5.46-5.21 5.21 5.21 0 0 1 5.5-5.21c3.71.02 5.15 2.7 5.15 5.26V12h-8.53zm6.37-1.51a2.78 2.78 0 0 0-3.07-2.89 3.19 3.19 0 0 0-3.3 2.89h6.37zm3-4.15h2.33l3.15 7.75 3-7.75h2.17l-5.05 12.06c-.72 1.72-1.41 2.89-3.63 2.89A5.18 5.18 0 0 1 96 21l.25-1.72a3.45 3.45 0 0 0 1.21.23c1.28 0 1.66-.65 2.06-1.63l.65-1.57-4.41-10z" class="b92747d9-14c1-46ff-8b3c-6d7694c1731c"/>
	<path d="M108.47 1.47h2.15v6.16h8.23V1.47H121V16.3h-2.15V9.51h-8.23v6.79h-2.15V1.47zm25.15 14.83h-2v-1.53a3.81 3.81 0 0 1-3.5 1.78 3.54 3.54 0 0 1-3.85-3.79V6.37h2v5.86a2.27 2.27 0 0 0 2.42 2.55c1.68 0 3-1 3-3.31v-5.1h2v9.93zm13.38-.09c0 3-2.34 5.11-5.81 5.11a7.47 7.47 0 0 1-5.2-1.78l1.35-1.54a5.1 5.1 0 0 0 3.79 1.61c3 0 3.83-1.76 3.84-3.43v-1.52h-.07a4.28 4.28 0 0 1-3.68 1.76 5.1 5.1 0 0 1-5.4-5.09 5.1 5.1 0 0 1 5.41-5.21 4.65 4.65 0 0 1 3.7 1.67V6.37h2v9.84zm-9-4.88a3.5 3.5 0 0 0 7 0 3.5 3.5 0 0 0-7 0zm16.86-5.21a5.41 5.41 0 0 1 5.64 5.21 5.67 5.67 0 0 1-11.3 0 5.42 5.42 0 0 1 5.64-5.21zm0 8.67a3.29 3.29 0 0 0 3.5-3.45 3.5 3.5 0 0 0-7 0 3.29 3.29 0 0 0 3.49 3.45z" class="e7849aa7-b960-44b2-b1bf-8cd6bddf76bd"/>
	<path d="M176.71 8v7.31a13.6 13.6 0 0 1-6 1.36c-5.38 0-8.49-3.58-8.49-7.79 0-4.4 3.44-7.79 8.28-7.79 2.91 0 4.68.73 5.92 1.93l-1.53 1.53A6.26 6.26 0 0 0 170.48 3a5.76 5.76 0 0 0-6 5.9 5.92 5.92 0 0 0 6.16 5.9 8.88 8.88 0 0 0 3.9-.77V9.89H171V8h5.67zm3.07-1.63h2V7.9A3.63 3.63 0 0 1 185 6.12a3.08 3.08 0 0 1 .9.13l-.09 2a4.19 4.19 0 0 0-1-.15c-2 0-3 1-3.05 3.18v5h-2V6.37zm13.09-.25a5.41 5.41 0 0 1 5.64 5.21 5.67 5.67 0 0 1-11.3 0 5.42 5.42 0 0 1 5.65-5.21zm0 8.67a3.29 3.29 0 0 0 3.5-3.45 3.5 3.5 0 0 0-7 0 3.28 3.28 0 0 0 3.49 3.45zm17.26 1.51h-2v-1.53a3.81 3.81 0 0 1-3.5 1.78 3.54 3.54 0 0 1-3.85-3.79V6.37h2v5.86a2.27 2.27 0 0 0 2.42 2.55c1.68 0 3-1 3-3.31v-5.1h2v9.93zm2.72-9.93h2v1.42a4.66 4.66 0 0 1 3.7-1.67 5.09 5.09 0 0 1 5.4 5.21 5.09 5.09 0 0 1-5.41 5.21 4.55 4.55 0 0 1-3.7-1.68v7.34h-2V6.37zm2 5a3.5 3.5 0 0 0 7 0 3.5 3.5 0 0 0-6.99-.04z" class="02d93889-0fb2-45e9-aa3c-bfb1baf7f55e"/>
</svg>
```

**Comment by dabutvin** [comment]
Hey @chrisblakley!  Thanks for the awesome repro and background info. This is super interesting.
This is super unfortunate and I want to track this down asap.

Can you confirm if you have any `.imgbotconfig` settings for your repo? Or are you using the default setup?

We should certainly upstream this bug to the svgo library.
Do you know if there is already an existing issue over at https://github.com/svg/svgo?

I think the best short term thing we can do is to go through the lossless plugins one by one and see which one of them is causing the issue and turn it off until we can get the bug fixed and released in svgo directly.
https://github.com/dabutvin/Imgbot/blob/master/CompressImagesFunction/Compressors/SvgoCompress.cs#L8

Thanks again for reporting this!

**Comment by chrisblakley** [comment]
I can confirm that my repos have all been using the default setup– no custom configuration files.

I looked around the SVGO repo issues and there were some loosely related conversations (nothing that seemed exact) but I was not confident enough in reporting anything there as I've never directly used SVGO– it's always been via another tool– so I would not be able to perform any requested CLI tests/checks.

Regarding the Imgbot plugins, I'm not sure how to check my hunches individually but I am pretty certain it will be within the `minifyStyles` or `convertStyleToAttrs` plugins.

I am able to also recreate this on the [SVGOMG too](https://github.com/jakearchibald/svgomg)l by @jakearchibald but again I was not confident enough in determining the root cause (and if was different than other issues) to create a new issue on that repo either. All I can re-create there is that the problem occurs when I toggle the `minifyStyles` or `removeStyleElement` input boxes.

Additionally, if it's any help, here is an Imgbot pull request that includes the problem as described: https://github.com/chrisblakley/Nebula/pull/2015
Ignoring the Font Awesome files, you can see the `logo.svg` and `offline.svg` images produce this problem. _Quick note– that offline image was previously accidentally merged from imgbot so that's why both the before and after files are all black._

Happy to provide any additional information if needed.

**Comment by Lemmingh** [comment]
@dabutvin
I don't think a `bug` should be closed automatically.

Please change bot's configuration and reopen these issues. Thanks.
