### ISSUE TITLE
Pull request not coming through

### ISSUE THREAD

**Issue by RandomRaine** [dabutvin/Imgbot#668]
Hi, I just purchased Imgbot 7hrs ago and requested a new pull a couple times and nothing is coming through. Am I missing something? Please advise.

**Comment by RandomRaine** [comment]
thats odd, never showed up in github. I did just receive an email let me know it finished...

**Comment by dlemstra** [comment]
Could be related to the issue that are happening now: https://www.githubstatus.com/
