### ISSUE TITLE
Remove "xmlns" in svg when using full compression　　

### ISSUE THREAD

**Issue by tamaosa** [dabutvin/Imgbot#701]
When aggressiveCompression is ture, "xmlns" in SVG are removed probably because svgo's removeXMLNS is enabled. As a result, SVG could not be displayed in my environment (website created by gatsby).

If svg is inline, it can safely remove the "xmlns".  So it need "xmlns" in many cases. My problem was also fixed by adding "xlmns". I think it might be had better  to to disable removeXMLNS.

Thank you for a great tool!

**Comment by dabutvin** [comment]
Thanks for reporting this issue. I think we probably need a place to supply custom SVGO options for these cases.
Then you could supply all the options you want on or off for the specific setup.

// .imgbotconfig
```
{
    "svgoPlugins": [
        "cleanupEnableBackground",
        "cleanupIDs",
        "collapseGroups",
        "convertPathData",
        "convertShapeToPath",
        "convertTransform",
        "..."
    ]
}
```

what do you think?

**Comment by tamaosa** [comment]
Thanks for the reply. That's a great idea!

Of course, we need to consider conflicts with `aggressiveCompression` options.

**Comment by TPS** [comment]
The title to this issue needs clarification.
