### ISSUE TITLE
Manually re-run imgbot

### ISSUE THREAD

**Issue by bergmeister** [dabutvin/ImgBot#72]
I see that I can configure a config file to setup a schedule for imgbot but it would be also nice to be able to have e.g. a button in the settings to re-run imgbot either on all or one specific repo as a one-off action

**Comment by dabutvin** [comment]
That's a great idea!

Right now imgbot will work Everytime you touch an image file off of the commit hook but I could see where you might just want to hit the button.

I think you could add GitHub authentication to the ImgBot.Web site to dump installations/repos and then have the website host a button that when clicked would queue an imageupdatemessage to the job on the back end with the repoName and installationId. This websites hosts the webhooks today so all the connections are already there.

Does that like what you are looking for?

**Comment by dabutvin** [comment]
We rolled out support for this today! Ended up putting together a page on the website.
https://imgbot.net/app/

You can request optimization per repo and see the status. If you get a chance to try it out and have any problems with it please feel free to open an issue :)
