### ISSUE TITLE
Colors change when using lossless compression

### ISSUE THREAD

**Issue by Naramsim** [dabutvin/Imgbot#725]
> This issue is a duplicate of https://github.com/dabutvin/Imgbot/issues/140. Which was closed in 2018.

We folks at PokeAPI tried to use your bot to optimize our sprites. However, we noted that the colors of the single pixels change. Is this intended? Even with lossless compression?

References (with examples) are: https://github.com/PokeAPI/sprites/pull/24 and https://github.com/PokeAPI/sprites/pull/25

I post the images also here, for convenience:

### original

![our](https://github.com/PokeAPI/sprites/blob/master/sprites/items/durin-berry.png?raw=true) ![our](https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/25.png?raw=true) ![our](https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/versions/generation-iv/diamond-pearl/13.png?raw=true) ![our](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/234.svg)

### imgbot's

![imgbot](https://github.com/PokeAPI/sprites/blob/imgbot/sprites/items/durin-berry.png?raw=true) ![imgbot](https://github.com/PokeAPI/sprites/blob/imgbot/sprites/pokemon/25.png?raw=true) ![imgbot](https://github.com/PokeAPI/sprites/blob/imgbot/sprites/pokemon/versions/generation-iv/diamond-pearl/13.png?raw=true) ![imgbot](https://raw.githubusercontent.com/PokeAPI/sprites/imgbot/sprites/pokemon/other/dream-world/234.svg)

You can use the color palette tool integrated into the Chrome console to inspect the pixels. But you can note easily note that the green berry is a lighter green in the imgbot image.

**Comment by Naramsim** [comment]
Our config, for reference:

```json
{
    "ignoredFiles": [],
    "aggressiveCompression": false,
    "compressWiki": false,
    "minKBReduced": 10
}
```

**Comment by dabutvin** [comment]
Hi @Naramsim thanks for reporting this issue!

I looked back and forth at imgbot vs original and I believe they are exactly the same colors.
I tried using the chrome inspector tool as well and im seeing the same exact colors
I also went pixel by pixel on the pngs using PIL python lib and checked the RGB colors between the imgbot branch and the original branch and each one was exactly the same.

Probably just the red/green rings causing an illusion?

**Comment by C-Garza** [comment]
I'm getting different color values from the third image, the worm looking one. For instance, the bottom of its nose before is #de5a52 and after is #df5a51. Can you confirm?

**Comment by Naramsim** [comment]
The issue is present on my side when the browser zoom is more than 100%. Could you please try to zoom in at 110% and re-do the color-picker test?

I don't know if this is a feature of Chrome or if the images are really different.

**Comment by dabutvin** [comment]
I just downloaded [original](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/13.png) and [optimized](https://raw.githubusercontent.com/PokeAPI/sprites/imgbot/sprites/pokemon/versions/generation-iv/diamond-pearl/13.png)

and got the same exact pixel counts on each. Not seeing any #df5a51 pixels in either image

```
5862 #7b8bee
142 #cd7310
109 #eeac41
99 #181818
43 #6a3908
30 #de5a52
27 #9c2920
21,#ffffff
20 #5a5a62
14 #945a08
11 #ffe67b
8 #8b8b94
7 #c5c5c5
6 #ee9c8b
1 #ffdecd
```

**Comment by C-Garza** [comment]
@dabutvin Sorry I meant to say in the Chrome Inspector Tool I was getting those different values at the bottom of the nose. 

I just downloaded the two images and they do appear to be the same colors. Maybe it's just the way Chrome is rendering the colors then?

**Comment by magical** [comment]
As I noted in https://github.com/PokeAPI/sprites/pull/24#issuecomment-667729085, some of the images have a gAMA chunk, which it seems like imgbot is stripping. This affects how the images are rendered. 

In general, there are several [chunk types](https://www.w3.org/TR/PNG/#11addnlcolinfo) in PNG which hold colorspace metadata that can affect how an image is rendered. I don't think an optimizer should strip these chunks unless asked. @dabutvin, can you confirm whether imgbot strips colorspace metadata and whether this is intentional?

**Comment by dabutvin** [comment]
Oh interesting! I'm not sure - will have to look into this further.

**Comment by dabutvin** [comment]
running pngcheck on the worm (13.png) looks like the gAMA chunk is being actually being added by imagemagick.

original:
```
File: original-13.png (676 bytes)
  chunk IHDR at offset 0x0000c, length 13
    80 x 80 image, 32-bit RGB+alpha, non-interlaced
  chunk vpAg at offset 0x00025, length 9
    unknown private, ancillary, safe-to-copy chunk
  chunk IDAT at offset 0x0003a, length 598
    zlib: deflated, 32K window, maximum compression
  chunk IEND at offset 0x0029c, length 0
No errors detected in original-13.png (4 chunks, 97.4% compression).
```

compressed:
```
File: imgbot-13.png (656 bytes)
  chunk IHDR at offset 0x0000c, length 13
    80 x 80 image, 4-bit palette, non-interlaced
  chunk gAMA at offset 0x00025, length 4: 0.45455
  chunk cHRM at offset 0x00035, length 32
    White x = 0.3127 y = 0.329,  Red x = 0.64 y = 0.33
    Green x = 0.3 y = 0.6,  Blue x = 0.15 y = 0.06
  chunk PLTE at offset 0x00061, length 45: 15 palette entries
  chunk tRNS at offset 0x0009a, length 1: 1 transparency entry
  chunk bKGD at offset 0x000a7, length 1
    index = 2
  chunk tIME at offset 0x000b4, length 7:  4 Aug 2020 09:54:42 UTC
  chunk IDAT at offset 0x000c7, length 339
    zlib: deflated, 4K window, maximum compression
  chunk tEXt at offset 0x00226, length 37, keyword: date:create
  chunk tEXt at offset 0x00257, length 37, keyword: date:modify
  chunk IEND at offset 0x00288, length 0
No errors detected in imgbot-13.png (11 chunks, 79.5% compression).
```

**Comment by Naramsim** [comment]
Cool @dabutvin, so in the end, our images lack this gAMA chunk, maybe because our images are old and had to be embedded in devices with low storage. 

I don't really know what this gAMA chunk brings in as a feature. But after the analysis of @dabutvin I'm even more confused. Should our images have this gAMA? And how `ImgBot`(`imagemagik`) computed this gAMA chunk?

**Comment by magical** [comment]
@dabutvin Ah, you're right. I got the before & after images mixed up, my apologies. This raises some questions though. Why is imgbot adding so many ancillary chunks (gAMA, cHRM, bKGD, tIME, caNv, tEXt)?

@Naramsim [Gamma correction](https://en.wikipedia.org/wiki/Gamma_correction) is a cheap kind of color correction that compensates for nonlinearity in some monitors.  It's fine for an image not to have a gAMA chunk (and some would [argue](https://hsivonen.fi/png-gamma/) that they shouldn't). Imgbot/imagemagick really shouldn't be making one up. Same goes for the cHRM chunk, which is another form of color correction.

**Comment by magical** [comment]
Any update on this?

**Comment by Naramsim** [comment]
Nothing @magical. Maybe it's better to close this issue (which is very related to PokeAPI) and you can open a new issue just to discuss _"Why is imgbot adding so many ancillary chunks (gAMA, cHRM, bKGD, tIME, caNv, tEXt)?"_
