### ISSUE TITLE
ImgBot commits should be verified

### ISSUE THREAD

**Issue by kenman345** [dabutvin/ImgBot#75]
Can you update ImgBot to use a PGP key for its commits so that its verified commits in our repository records? This would be nice for consistency.

**Comment by dabutvin** [comment]
hi @kenman345 thanks for opening an issue.

I have seen another repo that required signature as part of PR checks.

It looks like there is support for it

https://github.com/libgit2/libgit2sharp/pull/1304

we would just have to update here i think:
https://github.com/dabutvin/ImgBot/blob/master/ImgBot.Function/CompressImages.cs#L81

**Comment by kenman345** [comment]
quick look makes me think you're right about that. Would love to see this implmented

**Comment by dabutvin** [comment]
getting some help from nodegit and making some progress on this one

https://github.com/nodegit/nodegit/issues/1018#issuecomment-364938948

**Comment by kenman345** [comment]
is this deployed yet? I like the progress but still see imgbot commits are not verified still

**Comment by dabutvin** [comment]
@kenman345 I have a PR here https://github.com/dabutvin/ImgBot/pull/78

It is signing commits right now, but they are still showing as unverified in GitHub UI.
There is a mismatch in the PGP library being used to sign and the one being used to verify in GitHub.

I'm going to take a look and see where the mismatch is if I can find it

**Comment by kenman345** [comment]
thanks!

**Comment by dabutvin** [comment]
fixed via #78 

This is now enabled for all installations.
