### ISSUE TITLE
Is it possible to have ImgBot closes/delete the branch after PR merged?

### ISSUE THREAD

**Issue by kenman345** [dabutvin/ImgBot#82]
After we merge a PR fromImgBot, I have to make sure whichever team member it was also deletes the imgbot branch. Otherwise, It prevents imgbot from submitting another PR next time it should. So can it actually handle this instead? Maybe throw it into a configuration setting so it can be turned off but it be on by default?

**Comment by dabutvin** [comment]
Great idea. What would you call the config setting? Any ideas?

**Comment by kenman345** [comment]
Prunebranchaftermerge?

**Comment by dabutvin** [comment]
awesome.  Because this changes behavior for existing installs, I think keeping it off by default would be better for now.

**Comment by kenman345** [comment]
could be that you indicate it for a month on PRs so that people are aware. But really I'd say that the change is fairly harmless. If I have a configuration file to schedule once a day, I would want it to be able to delete the branch once merged or add to the PR at the scheduled time if that PR still hasnt merged.

**Comment by dabutvin** [comment]
Yeah, I see what you are coming from.

Adding another commit to an existing PR is an interesting case

**Comment by RohanNagar** [comment]
Is this an available option yet? I would like for ImgBot to delete its branches after I merge them

**Comment by dabutvin** [comment]
Hi @RohanNagar thanks for finding this stale issue!

Let's reactivate and get this in 'todo'

We can add a webhook to listen for 'imgbot' branch getting integrated and send a branch delete.

I think having this on by default would probably be fine after all. Having old imgbot branches hanging around has caused problems in the past anyways

**Comment by RohanNagar** [comment]
Don't think this is stale yet :smile:

**Comment by staabm** [comment]
@dabutvin maybe you should configure stale-bot to ignore certain issue which are labeled (e.g. with "help-wanted") or similar

**Comment by dabutvin** [comment]
@staabm I want help on almost everything around here lol

We can always dig the stale issues out of the closed bin https://github.com/dabutvin/ImgBot/issues?q=is%3Aissue+label%3Awontfix+is%3Aclosed

**Comment by dabutvin** [comment]
This is a nice implementation I've seen folks pairing with ImgBot to solve this problem
https://github.com/apps/delete-merged-branch
https://github.com/SvanBoxel/delete-merged-branch

**Comment by mrmajik45** [comment]
Dependabot deletes the Branch when merged

**Comment by Berkmann18** [comment]
As @mrmajik45 pointed out, you can take a look at dependabot who closes the branches after it got merged by either someone or the bot itself (note: it would be cool if it could also auto-merge it, say when the checks goes green).

**Comment by dabutvin** [comment]
yeah @dependabot-bot  is awesome!

We should do this! We have hooks on the imgbot branch already, if we see it merged, we can totally issue a delete.
Good idea about the auto-merge option, I opened #231 to track that - feel free to chime in if there's anything i missed

**Comment by EwoutH** [comment]
Can we reopen and fix this?

**Comment by dabutvin** [comment]
:+1:

**Comment by dabutvin** [comment]
I got #314 open to start doing this automatically

**Comment by dabutvin** [comment]
thanks all for pushing for this improvement.

It is now live in production

![image](https://user-images.githubusercontent.com/5168796/52542299-1b981d00-2d53-11e9-84c0-7ce6a11c34b2.png)

**Comment by yohighness317** [comment]
https://github.com/dabutvin/ImgBot/issues/82#
