### ISSUE TITLE
Imgbot changed the colors of my PNG image

### ISSUE THREAD

**Issue by rosslh** [dabutvin/Imgbot#827]
[Here's the pull request](https://github.com/rosslh/rosshill.ca/pull/232/files?short_path=dec3dbb#diff-dec3dbb22930805b92ae873aafa38185402ae3f6ff7338277ccfcc42e08a561d). The background color goes from `#212733` to `#1B2230`.

I assume this is a bug since Imgbot is supposed to be lossless.

**Comment by dlemstra** [comment]
What are you using to compare the images because this is what ImageMagick is telling me (patched the executable locally to print the PNG bKGD chunk):

```
I:\issues\imgbot>identify siteImage.png
    Reading PNG bKGD chunk, raw ping_background=(8481,10023,13107)
    bkgd_scale=257.  ping_background=(8481,10023,13107)
siteImage.png PNG 1200x628 1200x628+0+0 8-bit sRGB 19424B 0.000u 0:00.003

I:\issues\imgbot>identify siteImage.imgbot.png
    Reading PNG bKGD chunk, raw ping_background=(8481,10023,13107)
    bkgd_scale=257.  ping_background=(8481,10023,13107)
siteImage.imgbot.png PNG 1200x628 1200x628+0+0 8-bit sRGB 243c 7597B 0.000u 0:00.006

I:\issues\imgbot>compare -metric rmse siteImage.png siteImage.imgbot.png null:
0 (0)
```

They appear to be identical.

**Comment by rosslh** [comment]
Hi @dlemstra. I see the color difference when I open the images in a web browser (Firefox or Chrome). Here's the color difference I see (not just in GitHub's diff view):

![image](https://user-images.githubusercontent.com/8635605/104848378-ae805100-58b2-11eb-8b19-5fb28beabfa2.png)

You can use a color picker to confirm the color difference.

Strangely I don't see the color difference when I download and view the images with the built-in Photos app. My OS is `Windows 10 Home Version 10.0.18363 Build 18363`.

**Comment by IlanCosman** [comment]
This is the same issue as my own, #815. Perhaps we should consolidate these? It's seeming more and more likely that it's a browser related thing somehow.

**Comment by rosslh** [comment]
Closing in favor of #815
