### ISSUE TITLE
Shallow clone for better perf

### ISSUE THREAD

**Issue by dabutvin** [dabutvin/ImgBot#96]
Depth is not available from libgit but there may be some hacks to make it happen.

Repos with 100,000 commits+ take forever to clone right now

**Comment by dabutvin** [comment]
This is where the clone happens right now
https://github.com/dabutvin/ImgBot/blob/master/CompressImagesFunction/CompressImages.cs#L28

I don't have a lot of direction on how to pull this off, but decomposing the clone command may be a good place to start

**Comment by SuperSandro2000** [comment]
bump

**Comment by mwanchap** [comment]
Looks like this kind of thing is not supported in LibGit2Sharp yet...
https://github.com/libgit2/libgit2/issues/3058

**Comment by dabutvin** [comment]
Yeah, that's unfortunate.

Some ideas:

We *could* pick up that issue and add support for clone depth
We *could* ditch libgit for the clone part and shell out to `git.exe` using [Process.cs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netcore-2.1)

This is what they do in the Azure pipelines

https://github.com/Microsoft/azure-pipelines-agent/pull/620/files
https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/ProcessInvoker.cs#L168-L176

**Comment by dabutvin** [comment]
Hacktoberfest is over, but I would really like to experiment with something here

**Comment by dabutvin** [comment]
Opened up https://github.com/dabutvin/ImgBot/pull/259

**Comment by dabutvin** [comment]
had some success with this at first, but the implementation was too flaky. need to have another go at it and rethink the strategy.

It might be interesting to try the content APIs instead, no clone at all just download the file, creating a commit would be trickier for sure

https://developer.github.com/v3/git/trees/
https://developer.github.com/v3/repos/contents/#get-contents
